collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.9627400862518698
  brandStrength: 0.2989651395473629
  rhythmicContrast: 0.2602209106553346
  brandColors:
    - '#25064D'
    - '#36175E'
    - '#553285'
    - '#7B52AB'
    - '#9768D1'
  lightness: 0.3395432909019291
typography_spectrum: 1
layout_spectrum: 1
name: RivertownDigital
